---
# tasks file for ansible-role-zram

- name: Add zram module
  community.general.modprobe:
    name: zram
    state: present
    persistent: present

- name: Install startup template
  template:
    src: zram_start.sh.j2
    dest: /usr/local/sbin/zram_start.sh
    mode: 0755
  notify:
    - restart zram

- name: Install systemd template
  template:
    src: zram_systemd.service.j2
    dest: /etc/systemd/system/zram.service
  notify:
    - restart zram
  register: systemd

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: systemd.changed

- name: Start zram
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: false
    enabled: true
    name: zram
