---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
  roles:
    - name: ansible-role-zram

